# Generated by Django 4.2.23 on 2025-09-10 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_order_products_order_store_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='catigory',
            field=models.CharField(choices=[('ملابس رجالية', 'ملابس رجالية'), ('ملابس نسائية', 'ملابس نسائية'), ('ملابس أطفال', 'ملابس أطفال'), ('هواتف نقالة', 'هواتف نقالة'), ('إلكترونيات', 'إلكترونيات'), ('مأكولات', 'مأكولات'), ('صيدلي', 'صيدلي')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
