# Generated by Django 4.2.23 on 2025-10-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_store_catigory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='catigory',
            field=models.CharField(choices=[('ملابس رجالية', 'ملابس رجالية'), ('ملابس نسائية', 'ملابس نسائية'), ('ملابس أطفال', 'ملابس أطفال'), ('هواتف نقالة', 'هواتف نقالة'), ('إلكترونيات', 'إلكترونيات'), ('مأكولات', 'مأكولات'), ('صيدلي', 'صيدلي'), ('إكسسوارات', 'إكسسوارات')], max_length=255),
        ),
    ]
