# Generated by Django 4.2.23 on 2025-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epayement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(),
        ),
    ]
