# Generated by Django 4.2.23 on 2025-10-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epayement', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveBigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
