# Generated by Django 4.2.23 on 2025-10-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'مستخدم'), ('freelancer', 'freelancer'), ('teacher', 'مدرس'), ('delivery', 'عامل توصيل'), ('courses_instructor', 'إستاذ دورات'), ('seller', 'بائع'), ('consulter', 'مقدم إستشارات')], default='member', max_length=20),
        ),
    ]
